version:'3'
services: 
    server:
        image: node:14-alpine
        build: .
        ports:
            - 3000:3000
            container_name: jr-cms-13_server
            depends_on: 
                - mongo
                tty: true
                env_file: .env
                volumes:
                    - ./:/app
                    command: >
                    sh -c "cd /app && rm -rf node_modules/ &&npm i && npm run dev"
                
    mongo:
        image:mongo:4
        ports:
            - 27017:27017
            container_name: jr-cms-13_mongo
